name: ci-lint

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

    # Lint Dockerfiles
      - name: Lint Dockerfiles
        run: |
          echo "Linting Dockerfiles"
          for file in $(find . -name 'Dockerfile'); do
            echo "Checking $file"
            cat $file | docker run --rm -i hadolint/hadolint || true
          done

    # Lint Shell Scripts
      - name: Lint Shell Scripts
        run: |
          echo "Linting Shell Scripts"
          for file in $(find . -name '*.sh'); do
            echo "Checking $file"
            docker run --rm -v $(pwd):/mnt koalaman/shellcheck:stable /mnt/$file || true
          done
 
    # Lint Python Scripts
      - name: Install Python linters
        run: |
          echo "Installing Python linters"
          pip install flake8 pylint ruff
      - name: Lint Python Scripts
        run: |
          echo "Linting Python scripts"
          for file in $(find . -name '*.py'); do
            echo "Checking $file"
            flake8 $file --max-line-length=120 || true
            pylint $file --max-line-length=120 --disable="C0103,C0114,C0115" || true
            ruff check $file --line-length=120 --fix || true
          done
          
